# Generated by Django 5.1.8 on 2025-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='Key'),
        ),
    ]
